log_format ltsv "time:$time_iso8601\t"
                "host:$remote_addr\t"
                "method:$request_method\t"
                "uri:$request_uri\t"
                "protocol:$server_protocol\t"
                "status:$status\t"
                "size:$body_bytes_sent\t"
                "referer:$http_referer\t"
                "ua:$http_user_agent\t"
                "request_time:$request_time\t"
                "upstream_time:$upstream_response_time";

server {
  listen 80 default_server;

  access_log /var/log/nginx/access.ltsv.log ltsv;
  access_log /var/log/nginx/access.log;
  error_log  /var/log/nginx/error.log warn;

  client_max_body_size 10m;
  root /home/isucon/webapp/public/;
  location / {
    try_files $uri /index.html;
  }
  location /api/ {
    proxy_set_header Host $host;
    proxy_pass http://webapp:8080;
  }

  location /api/internal/ {
    allow 172.16.0.0/12;
    deny all;
    proxy_set_header Host $host;
    proxy_pass http://webapp:8080;
  }
}
